name: we_gather_application
description: A new Flutter application.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  expansion_tile_card:
  date_format:
  splashscreen:
  intl:
  http:
  get:
  get_storage:
  pin_entry_text_field:
  pin_code_text_field:
  pin_code_fields:
  lottie:
  image_picker: ^0.6.6+1
  titled_navigation_bar:
  rxdart:
  shared_preferences:
  dio: ^3.0.8
  path: ^1.6.4
  file_picker: ^1.4.3+2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.0
flutter_icons:
  android: true
  image_path: "assets/wegather.png"
flutter:
  uses-material-design: true
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
