const Map<String, String> en = {
  'First Name': 'First Name',
  'Last Name': 'Last Name',
  '*Required': '*Required',
  'Email': 'Email',
  'Phone': 'Phone',
  'Password': 'Password',
  'Upload image': 'Upload image',
  'Register': 'Register',
  'Sign Up': 'Sign Up',
  'Sign In': 'Sign In',
  'Login': 'Login',
  'Forget Password': 'Forget Password',
  'Create Account': 'Create Account',
  'Register as': 'Register as',
  'User': 'User',
  'Organizer': 'Organizer',
  'Sign In as': 'Sign In as',
  'Admin': 'Admin',
  'Newest Events': 'Newest Events'
};
